env:
  browser: true
  es6: true
  node: true
  es2022: true
  jest: true
extends:
  - airbnb
parserOptions:
  ecmaVersion: 13
rules:
  max-depth: [‘error’, 2]
  max-lines-per-function: [‘error’, 10]
